# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_navigation:
    type: sylius.resource
    resource: |
        alias: nucms.navigation
        section: admin
        templates: NugatoNuCmsBundle:Admin/Crud
        grid: nucms_admin_navigation
        redirect: update
