# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_partial_taxon:
    resource: "partial/taxon.yml"
    prefix: /taxons

nucms_admin_partial_navigation:
    resource: "partial/navigation.yml"
    prefix: /navigations
