# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_admin_taxon:
    type: sylius.resource
    resource: |
        alias: nucms.taxon
        section: admin
        templates: NugatoNuCmsBundle:Admin/Taxon
        grid: nucms_admin_taxon
        redirect: update
