language: php

dist: precise

sudo: required

php:
    - 7.1

branches:
    only:
    - master
    - dev

env:
    global:
        - NUCMS_CACHE_DIR=$HOME/.nucms-cache
        - NUCMS_BUILD_DIR=etc/build
        - TRAVIS_NODE_VERSION="7.5"

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - vendor
        - node_modules
        - NUCMS_CACHE_DIR

install:
    - composer update

script:
    - composer validate --strict
    - bin/phpspec run --no-interaction -f dot