# This file is part of the NuCms package.
# (c) Jacek Bednarek

parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
