# This file is part of the NuCms package.
# (c) Jacek Bednarek

default:
    suites:
        admin_security:
            contexts:
                - Nugato\Behat\Context\Setup\DoctrineContext:
                    entityManager: '@doctrine.orm.entity_manager'

                - Nugato\Behat\Context\Setup\LocaleContext:
                    localeFactory: '@nucms.factory.locale'
                    localeRepository: '@nucms.repository.locale'

                - Nugato\Behat\Context\Setup\Admin\UserContext:
                    userFactory: '@nucms.factory.user'
                    userRepository: '@sylius.repository.admin_user'

                - Nugato\Behat\Context\Ui\Admin\SecurityContext:
            filters:
                tags: "@admin_security && @ui"
