# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    nucms.controller.web.page:
        class: Nugato\Bundle\NuCmsBundle\Controller\Web\PageController
        arguments:
            - '@nucms.context.locale.request_based_with_default'
            - '@sylius.locale_provider'
            - '@nucms.repository.page'
        tags: ['controller.service_arguments']

    nucms.controller.web.locale_switch:
        class: Nugato\Bundle\NuCmsBundle\Controller\Web\LocaleSwitchController
        arguments:
            - '@nucms.context.locale.request_based_with_default'
            - '@sylius.locale_provider'
        tags: ['controller.service_arguments']
