# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    nucms.file.filesystem:
        class: Gaufrette\Filesystem
        factory: 'knp_gaufrette.filesystem_map:get'
        arguments: ['%nucms.file.uploader.filesystem%']

    nucms.file.filename_generator:
        class: Nugato\Bundle\NuCmsBundle\Service\File\NameWithUniqueFilenameGenerator

    nucms.file.file_uploader:
        class: Nugato\Bundle\NuCmsBundle\Service\File\FileUploader
        arguments:
            - '@nucms.file.filesystem'
            - '@nucms.file.filename_generator'
