# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    nucms.navigation.form.type:
        class: Nugato\Bundle\NuCmsBundle\Form\Navigation\NavigationType
        tags:
            - { name: form.type }
        arguments: ['%nucms.model.navigation.class%', ['sylius']]

#    nucms.navigation_item.form.type:
#        class: Nugato\Bundle\NuCmsBundle\Form\Navigation\NavigationItemType
#        tags:
#            - { name: form.type }
#        arguments: ['%nucms.model.navigation_item.class%', ['sylius']]
