# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    nucms.navigation.form.type:
        class: Nugato\Bundle\NuCmsBundle\Form\Navigation\NavigationType
        tags:
            - { name: form.type }
        arguments: ['%nucms.model.navigation.class%', ['sylius']]

    # Fixtures
    nucms.fixture.navigation:
        class: Nugato\Bundle\NuCmsBundle\Fixture\NavigationFixture
        arguments:
            - '@nucms.factory.navigation'
            - '@nucms.manager.navigation'
        tags: [sylius_fixtures.fixture]

    nucms.fixture.navigation_item:
        class: Nugato\Bundle\NuCmsBundle\Fixture\NavigationItemFixture
        arguments:
            - '@nucms.factory.navigation_item'
            - '@nucms.factory.navigation_item_translation'
            - '@nucms.repository.navigation'
            - '@nucms.manager.navigation_item'
        tags: [sylius_fixtures.fixture]
