# This file is part of the NuCms package.
# (c) Jacek Bednarek

services:
    nucms.page.form.type:
        class: Nugato\Bundle\NuCmsBundle\Form\PageType
        tags:
            - { name: form.type }
        arguments: ['%nucms.model.page.class%', ['sylius']]
    nucms.page_translation.form.type:
        class: Nugato\Bundle\NuCmsBundle\Form\PageTranslationType
        tags:
            - { name: form.type }
        arguments: ['%nucms.model.page_translation.class%', ['sylius']]
