# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    #admin
    - suites/ui/admin/security.yml
    - suites/ui/admin/managing_pages.yml

    #web
    - suites/ui/web/displaying_pages.yml
