# This file is part of the NuCms package.
# (c) Jacek Bednarek

default:
    suites:
        web_displaying_pages:
            contexts:
                - Nugato\Behat\Context\Setup\DoctrineContext:
                    entityManager: '@doctrine.orm.entity_manager'

                - Nugato\Behat\Context\Setup\LocaleContext:
                    localeFactory: '@nucms.factory.locale'
                    localeRepository: '@nucms.repository.locale'

                - Nugato\Behat\Context\Setup\PageContext:
                    pageFactory: '@nucms.factory.page'
                    pageRepository: '@nucms.repository.page'

                - Nugato\Behat\Context\Ui\Web\DisplayingPagesContext:
            filters:
                tags: "@web_displaying_pages && @ui"
