# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    - { resource: "@NugatoNuCmsBundle/Resources/config/services.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/resources.yml" }

fos_rest:
    exception: ~
    view:
        formats:
            json: true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }