# This file is part of the NuCms package.
# (c) Jacek Bednarek

parameters:
    admin_prefix: 'admin'

imports:
    - { resource: "@NugatoNuCmsBundle/Resources/config/services.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/resources.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/grids.yml" }
    - { resource: "@NugatoNuCmsBundle/Resources/config/users.yml" }

# FosRestBundle Configuration
fos_rest:
    exception: ~
    view:
        formats:
            json: true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
