# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    - { resource: 'grids/admin/page.yml' }
    - { resource: 'grids/admin/locale.yml' }

sylius_grid:
    templates:
        action:
            update: '@NugatoNuCms/Admin/Crud/Action/update.html.twig'
