# This file is part of the NuCms package.
# (c) Jacek Bednarek

nugato_nu_cms_homepage:
    path:     /
    defaults: { _controller: NugatoNuCmsBundle:Default:index }

nucms_page:
    resource: routing/page.yml
