# This file is part of the NuCms package.
# (c) Jacek Bednarek

imports:
    - { resource: "services/controller.yml" }
    - { resource: "services/locale.yml" }
    - { resource: "services/page.yml" }
    - { resource: "services/navigation.yml" }

services:
    pagerfanta.view.uikit:
        class: Nugato\Bundle\NuCmsBundle\Pagination\UiKitView
        public: false
        tags:
            - { name: 'pagerfanta.view', alias: 'ui_kit' }
