# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Entity\AdminUser
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    form: Sylius\Bundle\UserBundle\Form\Type\UserType
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
