# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Entity\User\User
                    interface: Sylius\Component\User\Model\UserInterface
        oauth:
            user:
                classes:
                    model: Nugato\Bundle\NuCmsBundle\Entity\User\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
