# This file is part of the NuCms package.
# (c) Jacek Bednarek

nucms_web_homepage:
    path: /
    defaults: { _controller: nucms.controller.web.page:homePage }

nucms_web_homepage_locale:
    path: /{_locale}/
    defaults: { _controller: nucms.controller.web.page:homePage, _locale: '%locale%' }
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

nucms_web_single_page:
    path: /{_locale}/{slug}
    defaults: { _controller: nucms.controller.web.page:singlePage, _locale: '%locale%' }
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

nucms_web_locale_switch:
    path: /locale-switch/{code}
    methods: [GET]
    defaults:
        _controller: nucms.controller.web.locale_switch:switch
