# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_grid:
    grids:
        nucms_admin_locale:
            driver:
                name: doctrine/orm
                options:
                    class: Nugato\Bundle\NuCmsBundle\Entity\Locale
            fields:
                code:
                    type: string
                    label: nucms.ui.locale.name
                    sortable: ~
            filters:
                code:
                    type: string
