# This file is part of the NuCms package.
# (c) Jacek Bednarek

sylius_grid:
    grids:
        nucms_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: Nugato\Bundle\NuCmsBundle\Entity\Page
            fields:
                title:
                    type: string
                    label: nucms.ui.title
                    sortable: ~
            filters:
                title:
                    type: string